### ISSUE TITLE
Add company

### ISSUE THREAD

**Issue by louisdeveseleer** [fernandofeitosa/companies-using-flutter-list#1]
Awesome initiative!
At my current company we also use Flutter.
Company: Rella
Tags: Mobile
Size: 10-20
Location: USA
Remote: yes, only remote
Industry: Social media management (not sure where that fits)
Links: https://www.rellasocial.com/

**Comment by fernandofeitosa** [comment]
Thank you! I just added all the companies to the Readme file so everyone can contribute, I assumed you only hire remote in the US, but if that's not correct feel free to open a PR to fix. :)
