### ISSUE TITLE
iFood 

### ISSUE THREAD

**Issue by jehhxuxu** [fernandofeitosa/companies-using-flutter-list#2]
iFood is the largest food-tech in Latin America.

We have 2 apps.
iFood for Partners
https://medium.com/ifood-engineering/writing-the-new-ifood-for-partners-part-1-flutter-2-0-33aed81ffeec
https://medium.com/ifood-engineering/writing-the-new-ifood-for-partners-part-2-to-bloc-or-not-to-bloc-7ddedd389255

iFood Benefits
https://apps.apple.com/br/app/ifood-benef%C3%ADcios/id1550867930

**Comment by fernandofeitosa** [comment]
Obrigado! I just added all the companies to the Readme file so everyone can contribute, I assumed you hire remote only in Brazil, but if that's not correct feel free to open a PR to fix or let me know. :)
